### ISSUE TITLE
Pin messages sent by attendees

### ISSUE THREAD

**Issue by alxlion** [ClaperCo/Claper#42]
### Manager

Add a toggle "Show only pinned messages".

![CleanShot 2023-10-20 at 11 01 54](https://github.com/ClaperCo/Claper/assets/1835726/15aa6856-b224-4d8e-85db-b4ec92dbc733)

Add a "Pin"/"Unpin" action to a message
![CleanShot 2023-10-20 at 11 03 17](https://github.com/ClaperCo/Claper/assets/1835726/d34d2495-b613-401d-9362-97c880e8857c)

On the messages box, with all messages, show the pinned messages first.

### Presenter

Show only pinned messages in the presenter if toggle "Show only pinned messages" is enabled.

### Attendees view

Add a "Pinned" flag to a message when `pinned` = true

![CleanShot 2023-10-20 at 11 09 57](https://github.com/ClaperCo/Claper/assets/1835726/4ede2fcd-1a6f-4b36-9e9c-1b34e4aa2608)

Use this icon:

```
<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-pin-filled" width="12" height="12" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
   <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
   <path d="M15.113 3.21l.094 .083l5.5 5.5a1 1 0 0 1 -1.175 1.59l-3.172 3.171l-1.424 3.797a1 1 0 0 1 -.158 .277l-.07 .08l-1.5 1.5a1 1 0 0 1 -1.32 .082l-.095 -.083l-2.793 -2.792l-3.793 3.792a1 1 0 0 1 -1.497 -1.32l.083 -.094l3.792 -3.793l-2.792 -2.793a1 1 0 0 1 -.083 -1.32l.083 -.094l1.5 -1.5a1 1 0 0 1 .258 -.187l.098 -.042l3.796 -1.425l3.171 -3.17a1 1 0 0 1 1.497 -1.26z" stroke-width="0" fill="currentColor"></path>
</svg>
```

Use an SVG file like the "Host" badge.

## Back

When "Show only pinned messages" toggle is changed, change the `show_only_pinned` value of the `presentation_states` table and broadcast the change to all (presenter + manager + attendees).

When "Pin"/"Unpin" on Manager is clicked on a message, change the `pinned` value of a message (`posts` table)

## Database

Add a new column `show_only_pinned` (bool) to `presentation_states` table.

Add a new column `pinned` (bool) to `posts` table.

**Comment by haruncurak** [comment]
Hey @alxlion, I'd love to work on this! I'm wondering if you can provide a bit more details for the bounty before I get going? 

I'll claim it for now as I look into the codebase, hope nobody minds
/claim #42

**Comment by alxlion** [comment]
@haruncurak Sorry, I forgot the specs. I edited the first message. I hope it's enough for you, do no hesitate if you have questions and if you have some ideas/improvement to the original specs.

Thanks 🙏

**Comment by haruncurak** [comment]
Thank you! I'll get to it this afternoon and keep you posted over the weekend -

**Comment by haruncurak** [comment]
Some updates:

<img width="438" alt="Screenshot 2023-10-22 at 12 04 24 PM" src="https://github.com/ClaperCo/Claper/assets/53381119/3489bbeb-cd62-4ff8-a15a-d43e5a3451cd">
<img width="493" alt="Screenshot 2023-10-22 at 12 04 42 PM" src="https://github.com/ClaperCo/Claper/assets/53381119/7e762fc1-39fe-4bc2-ba22-4fcf16c02ab4">

Hit a small roadblock since the Messages component in Manage renders according to the phx-update="append" method, but we need phx-update="replace" for pinning messages and putting them up top in real time. Working on that at the moment.

**Comment by alxlion** [comment]
Great 😊 let me know if you are stuck

**Comment by haruncurak** [comment]
Hey @alxlion, I've finished up with this issue. Let me know if you would like to add more features moving forward! 

It took a bit of extra elbow grease since the phx-update interacts with the socket append() and update() in strange ways at times. I fixed all of that up, and ensured there were no visual bugs when pinning/unpinning. Sharing a quick video here: https://streamable.com/3eaxmy

Thanks!

**Comment by alxlion** [comment]
Thanks a lot @haruncurak for your submission, nice work! 

I will test the PR this weekend to validate the bounty after that.

**Comment by alxlion** [comment]
Merged ! Will be on the next release.

**Comment by haruncurak** [comment]
Amazing!! Happy to keep contributing -
